/*
 * comm_error_code.h
 *
 * 错误码
 * 
 */

#ifndef __COMM_ERR_CODE_H_
#define __COMM_ERR_CODE_H_

#ifdef __cplusplus
extern "C" {
#endif

#define MAKE_INFO(_base_, _num_)  ((unsigned int)((_base_) | (_num_)))

/* definition of error code */
#define LUX_OK                  (0)
#define LUX_ERR                 (-1)
#define LUX_ERR_CODE_BASE       (0x20000)                  /*系统错误*/

/* 基础功能模块，不可用作返回参数 */
#define LUX_ERR_CODE_ISP	(LUX_ERR_CODE_BASE + 0x1000)    /*ISP模块*/
#define LUX_ERR_CODE_FSRC	(LUX_ERR_CODE_BASE + 0x2000)    /*视频输出，framesource*/
#define LUX_ERR_CODE_IVS	(LUX_ERR_CODE_BASE + 0x3000)    /*智能算法*/
#define LUX_ERR_CODE_OSD	(LUX_ERR_CODE_BASE + 0x4000)    /*osd叠加*/
#define LUX_ERR_CODE_ENC	(LUX_ERR_CODE_BASE + 0x5000)    /*视频编码*/
#define LUX_ERR_CODE_DEC	(LUX_ERR_CODE_BASE + 0x6000)    /*视频解码*/
#define LUX_ERR_CODE_AUD	(LUX_ERR_CODE_BASE + 0x7000)    /*音频*/
#define LUX_ERR_CODE_EVENT	(LUX_ERR_CODE_BASE + 0x8000)    /*消息事件*/
#define LUX_ERR_CODE_WIFI	(LUX_ERR_CODE_BASE + 0x9000)    /*无线wifi*/
#define LUX_ERR_CODE_GLOBAL	(LUX_ERR_CODE_BASE + 0xA000)    /*全局common*/
#define LUX_ERR_CODE_INI	(LUX_ERR_CODE_BASE + 0xB000)    /*INI配置文件*/

/* 系统错误 */
#define LUX_SYS_NULL_PTR            MAKE_INFO(LUX_ERR_CODE_BASE, 0x2)
#define LUX_SYS_INVALID_PARM        MAKE_INFO(LUX_ERR_CODE_BASE, 0x3)
#define LUX_SYS_MALLOC_FAILED       MAKE_INFO(LUX_ERR_CODE_BASE, 0x4)
#define LUX_SYS_NOT_SUPPORTED       MAKE_INFO(LUX_ERR_CODE_BASE, 0x5)
#define LUX_SYS_NETWORK_ERROR       MAKE_INFO(LUX_ERR_CODE_BASE, 0x6)
#define LUX_SYS_RESRC_NOT_READY  	MAKE_INFO(LUX_ERR_CODE_BASE, 0x7)
#define LUX_SYS_FILE_NOT_FIND       MAKE_INFO(LUX_ERR_CODE_BASE, 0x8)
#define LUX_SYS_BIND_ERROR          MAKE_INFO(LUX_ERR_CODE_BASE, 0x9)
#define LUX_SYS_UNBIND_ERROR        MAKE_INFO(LUX_ERR_CODE_BASE, 0xa)

/*视频输出，framesource*/
#define LUX_FSRC_ALREADY_INIT               MAKE_INFO(LUX_ERR_CODE_FSRC, 0x1) 
#define LUX_FSRC_NO_INIT                    MAKE_INFO(LUX_ERR_CODE_FSRC, 0x2)

/* osd模块错误 */
#define LUX_OSD_INVALID_PARM                MAKE_INFO(LUX_ERR_CODE_OSD, 0x1)
#define LUX_OSD_CREATE_GROUP_ERR            MAKE_INFO(LUX_ERR_CODE_OSD, 0x2)
#define LUX_OSD_CREATE_REGION_ERR  			MAKE_INFO(LUX_ERR_CODE_OSD, 0x3)

/*isp模块错误*/
#define LUX_ISP_INVALID_PARM                MAKE_INFO(LUX_ERR_CODE_ISP, 0x1)
#define LUX_ISP_NULL_PTR                    MAKE_INFO(LUX_ERR_CODE_ISP, 0x2)                   

/* video模块错误 */
#define LUX_VIDEO_INVALID_PARM          MAKE_INFO(LUX_ERR_CODE_ENC, 0x1)
#define LUX_VIDEO_NULL_PRT              MAKE_INFO(LUX_ERR_CODE_ENC, 0x2)
#define LUX_VIDEO_CHAN_START_ERR        MAKE_INFO(LUX_ERR_CODE_ENC, 0x3)
#define LUX_VIDEO_CHAN_STOP_ERR         MAKE_INFO(LUX_ERR_CODE_ENC, 0x4)
#define LUX_VIDEO_GET_STREAM_ERR        MAKE_INFO(LUX_ERR_CODE_ENC, 0x5)
#define LUX_VIDEO_RLS_STREAM_ERR        MAKE_INFO(LUX_ERR_CODE_ENC, 0x6)
#define LUX_VIDEO_CHAN_CREATE_ERR       MAKE_INFO(LUX_ERR_CODE_ENC, 0x7)
#define LUX_VIDEO_CHAN_DESTROY_ERR      MAKE_INFO(LUX_ERR_CODE_ENC, 0x8)
#define LUX_VIDEO_CHAN_PARAM_ERR        MAKE_INFO(LUX_ERR_CODE_ENC, 0x9)
#define LUX_VIDEO_MALLOC_ERR            MAKE_INFO(LUX_ERR_CODE_ENC, 0xa)
#define LUX_VIDEO_REQUEST_IDR_ERR       MAKE_INFO(LUX_ERR_CODE_ENC, 0xb)
#define LUX_VIDEO_GET_ATTR_ERR          MAKE_INFO(LUX_ERR_CODE_ENC, 0xc)

/* audio 模块错误 */
#define LUX_AUDIO_INVALID_PARM          MAKE_INFO(LUX_ERR_CODE_AUD, 0x1)
#define LUX_AUDIO_NULL_PRT              MAKE_INFO(LUX_ERR_CODE_AUD, 0x2)
#define LUX_AUDIO_CHAN_START_ERR        MAKE_INFO(LUX_ERR_CODE_AUD, 0x3)
#define LUX_AUDIO_CHAN_STOP_ERR         MAKE_INFO(LUX_ERR_CODE_AUD, 0x4)
#define LUX_AUDIO_GET_STREAM_ERR        MAKE_INFO(LUX_ERR_CODE_AUD, 0x5)
#define LUX_AUDIO_RLS_STREAM_ERR        MAKE_INFO(LUX_ERR_CODE_AUD, 0x6)
#define LUX_AUDIO_CHAN_CREATE_ERR       MAKE_INFO(LUX_ERR_CODE_AUD, 0x7)
#define LUX_AUDIO_CHAN_DESTROY_ERR      MAKE_INFO(LUX_ERR_CODE_AUD, 0x8)
#define LUX_AUDIO_CHAN_PARAM_ERR        MAKE_INFO(LUX_ERR_CODE_AUD, 0x9)
#define LUX_AUDIO_MALLOC_ERR            MAKE_INFO(LUX_ERR_CODE_AUD, 0xa)
#define LUX_AUDIO_REQUEST_IDR_ERR       MAKE_INFO(LUX_ERR_CODE_AUD, 0xb)
#define LUX_AUDIO_GET_ATTR_ERR          MAKE_INFO(LUX_ERR_CODE_AUD, 0xc)
#define LUX_AUDIO_INIT_ERR              MAKE_INFO(LUX_ERR_CODE_AUD, 0xd)
#define LUX_AUDIO_CONF_ALG_ERR          MAKE_INFO(LUX_ERR_CODE_AUD, 0xe)
#define LUX_AUDIO_SND_FRAME_ERR         MAKE_INFO(LUX_ERR_CODE_AUD, 0xf)

/* 全局通用错误 */
#define LUX_INIT_MUTEX_ATTR_FAILED         MAKE_INFO(LUX_ERR_CODE_GLOBAL, 0x1)
#define LUX_SET_MUTEX_ATTR_FAILED          MAKE_INFO(LUX_ERR_CODE_GLOBAL, 0x2)
#define LUX_DESTROY_MUTEX_ATTR_FAILED      MAKE_INFO(LUX_ERR_CODE_GLOBAL, 0x3)
#define LUX_INIT_MUTEX_FAILED              MAKE_INFO(LUX_ERR_CODE_GLOBAL, 0x4)
#define LUX_MUTEX_LOCK_FAILED              MAKE_INFO(LUX_ERR_CODE_GLOBAL, 0x5)
#define LUX_MUTEX_TRYLOCK_FAILED           MAKE_INFO(LUX_ERR_CODE_GLOBAL, 0x6)
#define LUX_MUTEX_LOCK_BUSY                MAKE_INFO(LUX_ERR_CODE_GLOBAL, 0x7)
#define LUX_MUTEX_UNLOCK_FAILED            MAKE_INFO(LUX_ERR_CODE_GLOBAL, 0x8)
#define LUX_MUTEX_RELEASE_FAILED           MAKE_INFO(LUX_ERR_CODE_GLOBAL, 0x9)
#define LUX_CR_MUTEX_ERR                   MAKE_INFO(LUX_ERR_CODE_GLOBAL, 0xa)
#define LUX_MEM_PARTITION_EMPTY            MAKE_INFO(LUX_ERR_CODE_GLOBAL, 0xb)
#define LUX_MEM_PARTITION_FULL             MAKE_INFO(LUX_ERR_CODE_GLOBAL, 0xc)
#define LUX_MEM_PARTITION_NOT_FOUND        MAKE_INFO(LUX_ERR_CODE_GLOBAL, 0xd)
#define LUX_DONOT_FOUND_MODULE             MAKE_INFO(LUX_ERR_CODE_GLOBAL, 0xe)
#define LUX_PARM_NULL_PTR                  MAKE_INFO(LUX_ERR_CODE_GLOBAL, 0xf)
#define LUX_OPEN_FILE_ERR                  MAKE_INFO(LUX_ERR_CODE_GLOBAL, 0x10)
#define LUX_GET_INI_VALUE_ERR              MAKE_INFO(LUX_ERR_CODE_GLOBAL, 0x11)
/* comm模块错误 */
#define LUX_COMM_ZBAR_NOT_FOUND         MAKE_INFO(LUX_ERR_CODE_GLOBAL, 0x20)

/*IN配置文件*/
#define LUX_INI_LOAD_FILE_FULL          MAKE_INFO(LUX_ERR_CODE_INI, 0x1)
#define LUX_INI_GET_DIC_ATTR_FAILED     MAKE_INFO(LUX_ERR_CODE_INI, 0x2)
#define LUX_INI_GET_PARAM_FAILED        MAKE_INFO(LUX_ERR_CODE_INI, 0x3)
#define LUX_INI_SET_PARAM_FAILED        MAKE_INFO(LUX_ERR_CODE_INI, 0x4)
#define LUX_INI_OPEN_FILE_FAILED        MAKE_INFO(LUX_ERR_CODE_INI, 0x5)

/*ivs模块错误*/
#define LUX_IVS_GROUP_CREATE_ERR          MAKE_INFO(LUX_ERR_CODE_IVS, 0x0)
#define LUX_IVS_CHAN_CREATE_ERR           MAKE_INFO(LUX_ERR_CODE_IVS, 0x1)
#define LUX_IVS_CHAN_DESTROY_ERR          MAKE_INFO(LUX_ERR_CODE_IVS, 0x2)
#define LUX_IVS_CHAN_RIGISTER_ERR         MAKE_INFO(LUX_ERR_CODE_IVS, 0x3)
#define LUX_IVS_CHAN_UNRIGISTER_ERR       MAKE_INFO(LUX_ERR_CODE_IVS, 0x4)
#define LUX_IVS_SET_PARAM_ERR             MAKE_INFO(LUX_ERR_CODE_IVS, 0x5)
#define LUX_IVS_GET_PARAM_ERR             MAKE_INFO(LUX_ERR_CODE_IVS, 0x6)
#define LUX_IVS_START_RECIVE_PIC_ERR      MAKE_INFO(LUX_ERR_CODE_IVS, 0x7)
#define LUX_IVS_STOP_RECIVE_PIC_ERR       MAKE_INFO(LUX_ERR_CODE_IVS, 0x8)
#define LUX_IVS_CREAT_THREAD_ERR          MAKE_INFO(LUX_ERR_CODE_IVS, 0x9)
#define LUX_IVS_POLL_RESULT_ERR           MAKE_INFO(LUX_ERR_CODE_IVS, 0x10)
#define LUX_IVS_GET_RESULT_ERR            MAKE_INFO(LUX_ERR_CODE_IVS, 0x11)
#define LUX_IVS_RELEASE_RESULT_ERR        MAKE_INFO(LUX_ERR_CODE_IVS, 0x12)
#define LUX_IVS_CAPTURE_PIC_ERR           MAKE_INFO(LUX_ERR_CODE_IVS, 0x13)
#define LUX_IVS_SET_STARTCONFIG_ERR        MAKE_INFO(LUX_ERR_CODE_IVS, 0x14)

#ifdef __cplusplus
}
#endif
#endif

